kind: KubeletConfiguration
apiVersion: kubelet.config.k8s.io/v1beta1
cgroupDriver: "systemd"
address: "127.0.0.1"
staticPodPath: "/etc/kubernetes/manifests"
authentication:
  x509:
    clientCAFile: "/etc/kubernetes/pki/etcd/ca.crt"
    enabled: true
  webhook:
    enabled: false
  anonymous:
    enabled: false
authorization:
  mode: "AlwaysAllow"
